### ISSUE TITLE
Add absolute value function

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#1]
A common function that one may wish to use is the absolute value function. The absolute value function computes the distance a number is from 0.

For example:
`abs(5) = 5`
`abs(-5) = 5`
`abs(-0.2) = 0.2`

Rust has an absolute value function built in on all primitive numeric types. `x.abs()` will evaluate to the absolute value of `x`.

You will need to
* add absolute value function to the expression evaluator
* add support for parsing `abs` as a unary function

As an example, check out this commit where I added the tan function: 865d2221e7d29af6db2d9e9c31377932712156d6

If you are participating in hacktoberfest, please comment on this issue claiming it so others don't try to do the same work! Thank you!

**Comment by ridho9** [comment]
I would like to try this one

**Comment by z2oh** [comment]
Closed via #2
