### ISSUE TITLE
Allow for decimal input in the bounds input boxes

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#14]
The input boxes for bounds currently only allow for integers to be input. Ideally, we want to be able to input any numeric input (like `3.14` for instance).

The code for parsing the inputs is found here: https://github.com/z2oh/sexe/blob/master/src/interface.rs#L48-L76

It's a bit messy but a rule should be added for reading in the `.` character. Only one `.` character should be allowed in each input field.

**Comment by ajcpwnz** [comment]
Working on this 👍

**Comment by z2oh** [comment]
Great! Thanks @ajcpwnz
