### ISSUE TITLE
Add support for mathematical constants

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#22]
There are a host of mathematical constants that are of extreme importance in mathematics. It would be helpful to easily access these constants when writing a function.

To get started, we should add constants for the following:

* [Euler's number _e_](https://en.wikipedia.org/wiki/E_(mathematical_constant))
* [Pi _π_](https://en.wikipedia.org/wiki/Pi)

Euler's number should be parsed by `e` or `E`. Pi should be parsed by `pi`, `PI` or `π` (Rust has native unicode support -- let's use it!)

Note that these constants will need to be parsed before variables, since with the current parser, `e` will be parsed as the variable `e` (similar to `x`).

Also be careful that variable names can still start with these constants. The interface right now requires that the variable in the function be labeled explicitly with an `x`, but this could change in the future, and we want variables to be able to be called other things, like `eval` for example (not `e` the constant times `val` the variable!)

This may be trickier than it looks, but getting it right is important. I do not wish to discourage anyone from trying however! If you want to try then go for it! Feel free to post in this issue if you need any help or have any questions.

If you are participating in hacktoberfest, please comment on this issue claiming it so others don't try to do the same work! Thank you!

**Comment by duck2** [comment]
Taking up.

**Comment by z2oh** [comment]
Hey @duck2, there is an open PR that adds constants but the implementation has some issues. If you want to try as well then I would appreciate it, though I understand if you would want to move on to another issue. Thank you :)

**Comment by duck2** [comment]
I see, sorry for not checking the PRs section. #21 also looks interesting.

**Comment by z2oh** [comment]
Closed via #23
