### ISSUE TITLE
Add floor function

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#4]
A common function that one may wish to use is the floor function. The floor function computes the largest integer less than or equal to a number.

For example:
`floor(5) = 5`
`floor(4.5) = 4`
`floor(-0.2) = -1`

Rust has a floor function built in on all primitive numeric types. `x.floor()` will evaluate to the floor of `x`.

You will need to
* add floor function to the expression evaluator
* add support for parsing `floor` as a unary function

As an example, check out this commit where I added the tan function: 865d2221e7d29af6db2d9e9c31377932712156d6

If you are participating in hacktoberfest, please comment on this issue claiming it so others don't try to do the same work! Thank you!

**Comment by shreenaathia** [comment]
Hey, Can I work on this code?

**Comment by z2oh** [comment]
@shreenaathia sure! I'll remove the help wanted label.

**Comment by z2oh** [comment]
Hey @shreenaathia, how is this coming? If you have any questions, I would love to assist!

**Comment by shreenaathia** [comment]
Hey @z2oh, I am currently trying to build the code, but I am receiving an "  ^^^ Maybe a missing `extern crate sys;`? " error.  I am trying to work on a Windows computer and from what I can see online is that this library does not support Windows yet. Do you know a work around this ?

**Comment by z2oh** [comment]
@shreenaathia Hmm... I am not using Windows and will have trouble reproducing the issue. Can you post the output of `cargo build --verbose` when you run that in the project directory? I was not aware of incompatibilities with Windows.

**Comment by eloc3147** [comment]
@shreenaathia this seems to be an issue with the Termion crate. As far as I can tell, Termion doesn't currently support Windows. See the [Termion Readme](https://github.com/redox-os/termion).
So by extension, sexe will not compile on Windows.

However, after a quick test, sexe compiles and [runs ](https://user-images.githubusercontent.com/1409394/46793622-0d7db580-ccfb-11e8-85df-8d6be55e87d8.png)in [Windows Bash](https://docs.microsoft.com/en-us/windows/wsl/install-win10). You should be able to do all your development in that.

**Comment by z2oh** [comment]
Closed via f92f25ce9aac3aec121f30b7e6bd0ab8297c648a
