### ISSUE TITLE
Add ceil function

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#5]
A common function that one may wish to use is the ceil function. The ceil function computes the smallest integer greater than or equal to a number.

For example:
`ceil(4) = 4`
`ceil(0.4) = 1`
`ceil(-2.3) = -2`

Rust has a ceil function built in on all primitive numeric types. `x.ceil()` will evaluate to the ceil of `x`.

You will need to
* add ceil function to the expression evaluator
* add support for parsing `ceil` as a unary function

As an example, check out this commit where I added the tan function: 865d2221e7d29af6db2d9e9c31377932712156d6

If you are participating in hacktoberfest, please comment on this issue claiming it so others don't try to do the same work! Thank you!

**Comment by giantpanpan** [comment]
Hi can I work on this problem?

**Comment by z2oh** [comment]
@giantpanpan you sure can! I'll remove the help wanted label.

**Comment by giantpanpan** [comment]
@z2oh Thanks!

**Comment by z2oh** [comment]
Hey @giantpanpan! How is this coming along? If you have any questions, I'm always happy to help :)

**Comment by z2oh** [comment]
Closed via f92f25ce9aac3aec121f30b7e6bd0ab8297c648a
