### ISSUE TITLE
Add exp function

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#6]
A common function that one may wish to use is the exp function. The exp function computes the result of `e^x` for some number `x`.

For example:
`exp(0.5) ~= 1.64872`
`exp(0) ~= 2.7182818`
`exp(-3) ~= 0.049787`

Rust has an exp function built in on all primitive numeric types. `x.exp()` will evaluate to `e^x`.

You will need to
* add exp function to the expression evaluator
* add support for parsing `exp` as a unary function

As an example, check out this commit where I added the tan function: 865d2221e7d29af6db2d9e9c31377932712156d6

If you are participating in hacktoberfest, please comment on this issue claiming it so others don't try to do the same work! Thank you!

**Comment by boomshroom** [comment]
Saw Hacktoberfest on /r/rust and figured I'd see what's happening. I run into this when looking at tagged projects and it looks really cool! Mind if I try this out?

**Comment by z2oh** [comment]
@boomshroom Go for it! Thanks for helping!

**Comment by boomshroom** [comment]
Should I include exp2() and e while I'm at it?

**Comment by z2oh** [comment]
@boomshroom That would be great!

**Comment by boomshroom** [comment]
`exp2(x)` can be simulated with `2^x` and `e` could be ambiguous with scientific notation. That said it looks like variables can't have numbers immediately after them so it might not be a problem.

**Comment by z2oh** [comment]
I'm not sure what you mean. Variables can have numbers immediately after them. The variable is parsed as a coefficient multiplier of the variable. `2x` evaluates to the same values as `x2`.

However, function names are parsed greedily before variables, so `exp2(x)` must always parse the `exp2` first (before attempting to parse the `2` or the `x`.

But maybe I'm misunderstanding what it is you are saying?

**Comment by boomshroom** [comment]
I was referring to things like `5e2`. is that 10 * e, or 500? I figured that exp2 isn't really necessary because it's already possible to do `2^x`.

**Comment by z2oh** [comment]
Ah, yes that's true. `5e2` in this case gets the value 500: `5 * 10 ^ 2`. While it is true that `exp2` is redundant since `2^x` is already possible, `exp2` is a common enough function that it will be helpful to be able to invoke directly. There also may be some optimization potential, since [`exp2` is an LLVM intrinsic](https://llvm.org/docs/LangRef.html#llvm-exp2-intrinsic).

**Comment by z2oh** [comment]
Closed via #9
