### ISSUE TITLE
Add log2 function

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#7]
A common function that one may wish to use is the log2 function. The log2 function computes the logarithm base 2 of some number.

For example:
`log2(2) = 1`
`log2(8) = 3`
`log2(0.5) = -1`
`log2(1.5) ~= 0.584963`

Rust has a log2 function built in on all primitive numeric types. `x.log2()` will evaluate to the logarithm base 2 of `x`.

You will need to
* add log2 function to the expression evaluator
* add support for parsing `log2` as a unary function

Please note that log2 is not defined for non-positive numbers, so if the lower bound is 0 or below the program will crash. Don't worry about this for now, error handling will be added at a future date.

As an example, check out this commit where I added the tan function: 865d2221e7d29af6db2d9e9c31377932712156d6

If you are participating in hacktoberfest, please comment on this issue claiming it so others don't try to do the same work! Thank you!

**Comment by rtroxler** [comment]
Hi, can I claim this issue?

**Comment by z2oh** [comment]
@rtroxler Go for it!

**Comment by z2oh** [comment]
Closed via #10
