### ISSUE TITLE
Add log10 function

### ISSUE THREAD

**Issue by z2oh** [z2oh/sexe#8]
A common function that one may wish to use is the log10 function. The log10 function computes the logarithm base 10 of some number.

For example:
`log10(10) = 1`
`log10(1000) = 3`
`log10(5) ~= 0.69897`
`log10(0.5) ~= -0.30103`

Rust has a log10 function built in on all primitive numeric types. `x.log10()` will evaluate to the logarithm base 10 of `x`.

You will need to
* add log10 function to the expression evaluator
* add support for parsing `log10` as a unary function

Please note that log10 is not defined for non-positive numbers, so if the lower bound is 0 or below the program will crash. Don't worry about this for now, error handling will be added at a future date.

As an example, check out this commit where I added the tan function: 865d2221e7d29af6db2d9e9c31377932712156d6

If you are participating in hacktoberfest, please comment on this issue claiming it so others don't try to do the same work! Thank you!

**Comment by harsh183** [comment]
With reference to this issue and https://github.com/z2oh/sexe/issues/7, won't it be a better idea to write a ln(x) function and derive the remaining logs out of that?

**Comment by z2oh** [comment]
@harsh183 Rust has built in `log10` and `log2` functions on numeric types, so the functions that calculate these values are actually already written: no need to actually write them.

If these functions did not already exist, then deriving them from a common log function `ln(x)` would certainly be the way to go.

**Comment by z2oh** [comment]
The reason these functions are built in (instead of derived from `ln(x)`) is because LLVM (which Rust compiles to) defines these functions explicitly: https://llvm.org/docs/LangRef.html#llvm-log10-intrinsic

This is probably because `log10` and `log2` are so common, that CPUs/LLVM can do some very low level optimization that makes these two specific functions faster than if they are derived from `ln(x)`.

**Comment by harsh183** [comment]
Okay makes sense. I think I'll take these two up then, might be a few days due to college work though. (Ironically llvm is from my college so I should know it better)

**Comment by harsh183** [comment]
Well looks like the other is claimed so I'll take this. Thanks.

**Comment by z2oh** [comment]
@harsh183 I understand! I'll mark this issue claimed. Thanks!

**Comment by z2oh** [comment]
Closed via f92f25ce9aac3aec121f30b7e6bd0ab8297c648a.
